routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::get('home', 'HomeController@index');
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/tahun', 'Web\Admin\TahunController', ['as' => 'admin']);
Route::resource('admin/bulan', 'Web\Admin\BulanController', ['as' => 'admin']);
Route::resource('admin/kelompok', 'Web\Admin\KelompokController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::resource('admin/triwulan', 'Web\Admin\TriwulanController', ['as' => 'admin']);
Route::resource('admin/tahfidz', 'Web\Admin\TahfidzController', ['as' => 'admin']);
Route::resource('admin/rubah', 'Web\Admin\RubahController', ['as' => 'admin']);

Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');

Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/akadbarang', 'Web\Admin\AkadBarangController', ['as' => 'admin']);
Route::resource('admin/bangunrumah', 'Web\Admin\BangunRumahController', ['as' => 'admin']);
Route::get('admin/akadbarang/index/{id}', 'Web\Admin\AkadBarangController@index', ['as' => 'admin']);
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('admin/upload/regsim', 'Web\Admin\UploadController@regsim')->name('admin.upload.regsim');
Route::post('admin/import/regsim', 'Web\Admin\UploadController@import_regsim')->name('admin.import.regsim');

Route::get('admin/upload/regpem', 'Web\Admin\UploadController@regpem')->name('admin.upload.regpem');
Route::post('admin/import/regpem', 'Web\Admin\UploadController@import_regpem')->name('admin.import.regpem');

Route::get('admin/upload/bangunrumah', 'Web\Admin\UploadController@bangunrumah')->name('admin.upload.bangunrumah');
Route::post('admin/import/bangunrumah', 'Web\Admin\UploadController@import_bangunrumah')->name('admin.import.bangunrumah');

Route::get('admin/triwulan/show/{id}/{tw}', 'Web\Admin\TriwulanController@show_triwulan')->name('admin.triwulan.show.tw');
Route::get('admin/tahfidz/show/{id}/{tw}', 'Web\Admin\TahfidzController@show_tahfidz')->name('admin.tahfidz.show.tw');

app/Anggota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anggota extends Model
{
    protected $guarded = [];

    public function kelompok()
    {
        return $this->belongsTo('App\Kelompok', 'kelompok_id');
    }
    public function pekerjaan()
    {
        return $this->belongsTo('App\Pekerjaan', 'pekerjaan_id');
    }

    public function angsuran()
    {
        return $this->hasMany('App\Angsuran');
    }
    public function bangun()
    {
        return $this->hasMany('App\BangunRumah');
    }

    public function akad()
    {
        return $this->hasMany('App\Akad');
    }
}

app/Http/Controllers/Web/Admin/AnggotaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Anggota;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\AnggotaRequest;
use App\Kelompok;
use App\Pekerjaan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AnggotaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $data = Kelompok::orderBy('kelompok', 'ASC')->get()->all();
        return view('admin.anggota.beranda', compact('data', 'no'));
    }

    public function create()
    {
        $kelompok = Kelompok::orderBy('kelompok', 'ASC')->get()->all();
        $pekerjaan = Pekerjaan::orderBy('id', 'ASC')->get()->all();
        return view('admin.anggota.create', compact('kelompok', 'pekerjaan'));
    }

    public function store(AnggotaRequest $request)
    {
        $data = $request->all();
        Anggota::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Anggota " . $request->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Anggota "' . $request->nama . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.anggota.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $kelompok = Kelompok::orderBy('kelompok', 'ASC')->get()->all();
        $pekerjaan = Pekerjaan::orderBy('id', 'ASC')->get()->all();
        $data = Anggota::findOrFail($id);
        return view('admin.anggota.edit', compact('data', 'kelompok', 'pekerjaan'));
    }

    public function update(AnggotaRequest $request, $id)
    {
        $data = Anggota::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Anggota " . $request->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Anggota "' . $request->nama . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.anggota.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Anggota::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Anggota " . $data->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Anggota "' . $data->nama . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.anggota.index')->with($notification);
    }
}

resources/views/admin/anggota/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Anggota
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('admin.anggota.create') }}" class="btn btn-primary">+ Anggota</a><br><br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Anggota</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Anggota ID</th>
                                <th>Kelompok</th>
                                <th>Nama</th>
                                <th>NIK</th>
                                <th>Kd Rekening</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            @foreach($item->anggota->sortBy('nama') as $anggota)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $anggota->id }}</td>
                                <td>{{ $item->kelompok }}</td>
                                <td>{{ $anggota->nama }}</td>
                                <td>{{ $anggota->no_ktp }}</td>
                                <td>{{ $anggota->kode_rekening }}</td>
                                <td align="center">
                                    <form action="{{ route('admin.anggota.destroy',$anggota->id) }}" method="POST">
                                        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal-barang{{$anggota->id }}">Lihat</a>
                                        <a class="btn btn-success" href="{{ route('admin.anggota.edit',$anggota->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            <!-- Anggota -->
                            <div class="modal fade in" id="modal-barang{{$anggota->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span></button>
                                            <h4 class="modal-title">
                                                Data {{$anggota->nama}} | {{ $item->kelompok }}
                                            </h4>
                                        </div>
                                        <div class="box-body">
                                            @php
                                            $nop=1;
                                            @endphp
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                NIK
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->no_ktp }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Kd Rekekning
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->kode_rekening }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Kd Pembiayaan
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->kode_pembiayaan }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Pekerjaan
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->pekerjaan->pekerjaan }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                No Telp
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->no_telp }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Alamat
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->alamat }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Keterangan
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $anggota->ket }}
                                            </div>
                                        </div>
                                        <div class="box-footer">
                                            <button class="btn btn-default pull-left" data-dismiss="modal">Tutup</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/anggota/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Anggota
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data Anggota</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.anggota.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kelompok</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="kelompok_id">
                                        @foreach($kelompok as $kel)
                                        <option value="{{$kel->id}}">{{$kel->kelompok}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('kelompok_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nama</label>

                                <div class="col-sm-8">
                                    <input type="text" name="nama" class="form-control" placeholder="Nama">
                                    <small class="text-danger">{{ $errors->first('nama') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">NIK</label>

                                <div class="col-sm-8">
                                    <input type="number" name="no_ktp" class="form-control" placeholder="NIK">
                                    <small class="text-danger">{{ $errors->first('no_ktp') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kode Rekening</label>

                                <div class="col-sm-8">
                                    <input type="text" name="kode_rekening" class="form-control" placeholder="Kode Rekening">
                                    <small class="text-danger">{{ $errors->first('kode_rekening') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kode Pembiayaan</label>

                                <div class="col-sm-8">
                                    <input type="text" name="kode_pembiayaan" class="form-control" placeholder="Kode Pembiayaan">
                                    <small class="text-danger">{{ $errors->first('kode_pembiayaan') }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Alamat</label>

                                <div class="col-sm-8">
                                    <input type="text" name="alamat" class="form-control" placeholder="Alamat">
                                    <small class="text-danger">{{ $errors->first('alamat') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pekerjaan</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="pekerjaan_id">
                                        @foreach($pekerjaan as $pek)
                                        <option value="{{$pek->id}}">{{$pek->pekerjaan}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('pekerjaan_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">No Telp</label>

                                <div class="col-sm-8">
                                    <input type="text" name="no_telp" class="form-control" placeholder="No Telp">
                                    <small class="text-danger">{{ $errors->first('no_telp') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Keterangan</label>

                                <div class="col-sm-8">
                                    <input type="text" name="ket" class="form-control" placeholder="Keterangan">
                                    <small class="text-danger">{{ $errors->first('ket') }}</small>
                                </div>
                            </div>
                            
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/anggota')}}" class="btn btn-default  pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/anggota/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Anggota
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Anggota</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.anggota.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kelompok</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="kelompok_id">
                                        <option value="{{$data->kelompok_id}}">{{$data->kelompok->kelompok}}</option>
                                        @foreach($kelompok as $kel)
                                        <option value="{{$kel->id}}">{{$kel->kelompok}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('kelompok_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nama</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->nama}}" name="nama" class="form-control" placeholder="Nama">
                                    <small class="text-danger">{{ $errors->first('nama') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">NIK</label>

                                <div class="col-sm-8">
                                    <input type="number" value="{{$data->no_ktp}}" name="no_ktp" class="form-control" placeholder="NIK">
                                    <small class="text-danger">{{ $errors->first('no_ktp') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kode Rekening</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->kode_rekening}}" name="kode_rekening" class="form-control" placeholder="Kode Rekening">
                                    <small class="text-danger">{{ $errors->first('kode_rekening') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kode Pembiayaan</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->kode_pembiayaan}}" name="kode_pembiayaan" class="form-control" placeholder="Kode Pembiayaan">
                                    <small class="text-danger">{{ $errors->first('kode_pembiayaan') }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Alamat</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->alamat}}" name="alamat" class="form-control" placeholder="Alamat">
                                    <small class="text-danger">{{ $errors->first('alamat') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pekerjaan</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="pekerjaan_id">
                                        <option value="{{$data->pekerjaan_id}}">{{$data->pekerjaan->pekerjaan}}</option>
                                        @foreach($pekerjaan as $pek)
                                        <option value="{{$pek->id}}">{{$pek->pekerjaan}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('pekerjaan_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">No Telp</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->no_telp}}" name="no_telp" class="form-control" placeholder="No Telp">
                                    <small class="text-danger">{{ $errors->first('no_telp') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Keterangan</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->ket}}" name="ket" class="form-control" placeholder="Keterangan">
                                    <small class="text-danger">{{ $errors->first('ket') }}</small>
                                </div>
                            </div>
                            
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/anggota')}}" class="btn btn-default pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection