routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::get('home', 'HomeController@index');
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/tahun', 'Web\Admin\TahunController', ['as' => 'admin']);
Route::resource('admin/bulan', 'Web\Admin\BulanController', ['as' => 'admin']);
Route::resource('admin/kelompok', 'Web\Admin\KelompokController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::resource('admin/triwulan', 'Web\Admin\TriwulanController', ['as' => 'admin']);
Route::resource('admin/tahfidz', 'Web\Admin\TahfidzController', ['as' => 'admin']);
Route::resource('admin/rubah', 'Web\Admin\RubahController', ['as' => 'admin']);

Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');

Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/akadbarang', 'Web\Admin\AkadBarangController', ['as' => 'admin']);
Route::resource('admin/bangunrumah', 'Web\Admin\BangunRumahController', ['as' => 'admin']);
Route::get('admin/akadbarang/index/{id}', 'Web\Admin\AkadBarangController@index', ['as' => 'admin']);
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('admin/upload/regsim', 'Web\Admin\UploadController@regsim')->name('admin.upload.regsim');
Route::post('admin/import/regsim', 'Web\Admin\UploadController@import_regsim')->name('admin.import.regsim');

Route::get('admin/upload/regpem', 'Web\Admin\UploadController@regpem')->name('admin.upload.regpem');
Route::post('admin/import/regpem', 'Web\Admin\UploadController@import_regpem')->name('admin.import.regpem');

Route::get('admin/upload/bangunrumah', 'Web\Admin\UploadController@bangunrumah')->name('admin.upload.bangunrumah');
Route::post('admin/import/bangunrumah', 'Web\Admin\UploadController@import_bangunrumah')->name('admin.import.bangunrumah');

Route::get('admin/triwulan/show/{id}/{tw}', 'Web\Admin\TriwulanController@show_triwulan')->name('admin.triwulan.show.tw');
Route::get('admin/tahfidz/show/{id}/{tw}', 'Web\Admin\TahfidzController@show_tahfidz')->name('admin.tahfidz.show.tw');

app/Angsuran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Angsuran extends Model
{
    protected $guarded = [];
    public function anggota()
    {
        return $this->belongsTo('App\Anggota', 'anggota_id');
    }
    public function bulan()
    {
        return $this->belongsTo('App\Bulan', 'bulan_id');
    }
}

app/Http/Controllers/Web/Admin/AngsuranController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Anggota;
use App\Angsuran;
use App\Bulan;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\AngsuranRequest;
use App\Kelompok;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;

class AngsuranController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $tahun_id = Cookie::get('id_tahun');
        $bulan = Bulan::where('tahun_id',$tahun_id)->orderBy('id', 'ASC')->get()->all();
        $data = Kelompok::orderBy('kelompok', 'ASC')->get()->all();
        return view('admin.angsuran.beranda', compact('data', 'no','bulan'));
    }

    public function create()
    {
        //
    }

    public function store(AngsuranRequest $request)
    {
        $data = $request->all();
        Angsuran::create($data);

        $anggota = Anggota::where('id', $request->anggota_id)->get()->first();

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Angsuran atas nama " . $anggota->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Angsuran atas nama "' . $anggota->nama . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.angsuran.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $tahun_id = Cookie::get('id_tahun');
        $bulan = Bulan::where('tahun_id',$tahun_id)->orderBy('id', 'ASC')->get()->all();
        $kelompok = Kelompok::orderBy('kelompok', 'ASC')->get()->all();
        $data = Angsuran::findOrFail($id);
        return view('admin.angsuran.edit', compact('data','kelompok','bulan'));
    }

    public function update(AngsuranRequest $request, $id)
    {
        $data = Angsuran::findOrFail($id);
        
        $anggota = Anggota::where('id', $data->anggota_id)->get()->first();

        $data->update($request->all());


        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Angsuran atas nama " . $anggota->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Angsuran atas nama "' . $anggota->nama . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.angsuran.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Angsuran::findOrFail($id);

        $anggota = Anggota::where('id', $data->anggota_id)->get()->first();

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Angsuran atas nama " . $anggota->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Angsuran atas nama "' . $anggota->nama . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.angsuran.index')->with($notification);
    }
}

resources/views/admin/angsuran/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Angsuran
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Angsuran</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.angsuran.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Anggota</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="anggota_id">
                                        @foreach($data as $item)
                                        @foreach($item->anggota->sortBy('nama') as $anggota)
                                        <option value="{{$anggota->id}}">{{$item->kelompok}} | {{$anggota->nama}}</option>
                                        @endforeach
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('anggota_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Bulan</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="bulan_id">
                                        @foreach($bulan as $bul)
                                        <option value="{{$bul->id}}">{{$bul->bulan}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('bulan_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Angsuran</label>

                                <div class="col-sm-8">
                                    <input type="number" name="dana" class="form-control" placeholder="Angsuran">
                                    <small class="text-danger">{{ $errors->first('dana') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kelompok</th>
                                <th>Anggota</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            @foreach($item->anggota->sortBy('nama') as $anggota)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->kelompok }}</td>
                                <td>{{ $anggota->nama }}</td>
                                <td align="center">
                                    <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal-barang{{$anggota->id }}">Lihat</a>
                                </td>
                            </tr>
                            <!-- Angsuran -->
                            <div class="modal fade in" id="modal-barang{{$anggota->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span></button>
                                            <h4 class="modal-title">
                                                Data Angsuran - {{$anggota->nama}}
                                            </h4>
                                        </div>
                                        <div class="box-body">
                                            @php
                                            $nop=1;
                                            @endphp
                                            <div class="col-md-1">
                                                No
                                            </div>
                                            <div class="col-md-4">
                                                Bulan
                                            </div>
                                            <div class="col-md-4">
                                                Angsuran
                                            </div>
                                            <div class="col-md-3">
                                                Aksi
                                            </div>
                                        </div>
                                        @foreach($anggota->angsuran->sortBy('bulan_id') as $angsuran)
                                        <div class="box-body">
                                            <div class="col-md-1">
                                                {{$nop++}}
                                            </div>
                                            <div class="col-md-4">
                                                {{$angsuran->bulan->bulan}}
                                            </div>
                                            <div class="col-md-4">
                                                Rp. {{ number_format($angsuran->dana, 0, ".", ".")}},-
                                            </div>
                                            <div class="col-md-3">
                                                <form action="{{ route('admin.angsuran.destroy',$angsuran->id) }}" method="POST">
                                                    <a class="btn btn-success" href="{{ route('admin.angsuran.edit',$angsuran->id) }}"><span><i class="fa fa-edit"></i></span></a>
                                                    @csrf
                                                    @method('DELETE')

                                                    <button type="submit" class="btn btn-danger"><span><i class="fa fa-trash"></i></span></button>
                                                </form>
                                            </div>
                                        </div>
                                        @endforeach
                                        <div class="box-footer">
                                            <button class="btn btn-default pull-left" data-dismiss="modal">Tutup</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/angsuran/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Angsuran
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Angsuran</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.angsuran.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Anggota</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="anggota_id">
                                        <option value="{{$data->anggota_id}}">{{$data->anggota->kelompok->kelompok}} | {{$data->anggota->nama}}</option>
                                        @foreach($kelompok as $item)
                                        @foreach($item->anggota->sortBy('nama') as $anggota)
                                        <option value="{{$anggota->id}}">{{$item->kelompok}} | {{$anggota->nama}}</option>
                                        @endforeach
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('anggota_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Bulan</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="bulan_id">
                                        <option value="{{$data->bulan_id}}">{{$data->bulan->bulan}}</option>
                                        @foreach($bulan as $bul)
                                        <option value="{{$bul->id}}">{{$bul->bulan}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('bulan_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Angsuran</label>

                                <div class="col-sm-8">
                                    <input type="number" value="{{$data->dana}}" name="dana" class="form-control" placeholder="Angsuran">
                                    <small class="text-danger">{{ $errors->first('dana') }}</small>
                                </div>
                            </div>

                            <a href="{{url('admin/angsuran')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection