routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::get('home', 'HomeController@index');
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/tahun', 'Web\Admin\TahunController', ['as' => 'admin']);
Route::resource('admin/bulan', 'Web\Admin\BulanController', ['as' => 'admin']);
Route::resource('admin/kelompok', 'Web\Admin\KelompokController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::resource('admin/triwulan', 'Web\Admin\TriwulanController', ['as' => 'admin']);
Route::resource('admin/tahfidz', 'Web\Admin\TahfidzController', ['as' => 'admin']);
Route::resource('admin/rubah', 'Web\Admin\RubahController', ['as' => 'admin']);

Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');

Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/akadbarang', 'Web\Admin\AkadBarangController', ['as' => 'admin']);
Route::resource('admin/bangunrumah', 'Web\Admin\BangunRumahController', ['as' => 'admin']);
Route::get('admin/akadbarang/index/{id}', 'Web\Admin\AkadBarangController@index', ['as' => 'admin']);
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('admin/upload/regsim', 'Web\Admin\UploadController@regsim')->name('admin.upload.regsim');
Route::post('admin/import/regsim', 'Web\Admin\UploadController@import_regsim')->name('admin.import.regsim');

Route::get('admin/upload/regpem', 'Web\Admin\UploadController@regpem')->name('admin.upload.regpem');
Route::post('admin/import/regpem', 'Web\Admin\UploadController@import_regpem')->name('admin.import.regpem');

Route::get('admin/upload/bangunrumah', 'Web\Admin\UploadController@bangunrumah')->name('admin.upload.bangunrumah');
Route::post('admin/import/bangunrumah', 'Web\Admin\UploadController@import_bangunrumah')->name('admin.import.bangunrumah');

Route::get('admin/triwulan/show/{id}/{tw}', 'Web\Admin\TriwulanController@show_triwulan')->name('admin.triwulan.show.tw');
Route::get('admin/tahfidz/show/{id}/{tw}', 'Web\Admin\TahfidzController@show_tahfidz')->name('admin.tahfidz.show.tw');

app/Kelompok.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelompok extends Model
{
    protected $guarded = [];

    public function anggota()
    {
        return $this->hasMany('App\Anggota');
    }

    public function triwulan()
    {
        return $this->hasMany('App\Triwulan');
    }
}

app/Http/Controllers/Web/Admin/KelompokController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\KelompokRequest;
use App\Kelompok;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class KelompokController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $data = Kelompok::orderBy('kelompok', 'ASC')->get()->all();
        return view('admin.kelompok.beranda', compact('data', 'no'));
    }

    public function create()
    {
        //
    }

    public function store(KelompokRequest $request)
    {
        $data = $request->all();
        Kelompok::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Kelompok " . $request->kelompok;
        History::create($histori);

        $notification = array(
            'message' => 'Data Kelompok "' . $request->kelompok . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.kelompok.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Kelompok::findOrFail($id);
        return view('admin.kelompok.edit', compact('data'));
    }

    public function update(KelompokRequest $request, $id)
    {
        $data = Kelompok::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Kelompok " . $request->kelompok;
        History::create($histori);

        $notification = array(
            'message' => 'Data Kelompok "' . $request->kelompok . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.kelompok.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Kelompok::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Kelompok " . $data->kelompok;
        History::create($histori);

        $notification = array(
            'message' => 'Data Kelompok "' . $data->kelompok . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.kelompok.index')->with($notification);
    }
}

resources/views/admin/kelompok/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Kelompok
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Kelompok</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.kelompok.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kelompok</label>

                                <div class="col-sm-8">
                                    <input type="text" name="kelompok" class="form-control" placeholder="Kelompok / Tahap">
                                    <small class="text-danger">{{ $errors->first('kelompok') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jumlah Setoran</label>

                                <div class="col-sm-8">
                                    <input type="number" name="jml_setoran" class="form-control" placeholder="Jumlah Setoran">
                                    <small class="text-danger">{{ $errors->first('jml_setoran') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pembangunan Rumah</label>

                                <div class="col-sm-8">
                                    <input type="number" name="bangun_rumah" class="form-control" placeholder="Pembangunan Rumah">
                                    <small class="text-danger">{{ $errors->first('bangun_rumah') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>ID</th>
                                <th>Kelompok</th>
                                <th>Jumlah Setoran</th>
                                <th>Pembangun Rumah</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->id }}</td>
                                <td>{{ $item->kelompok }}</td>
                                <td>Rp. {{ number_format($item->jml_setoran, 0, ".", ".")}}</td>
                                <td>Rp. {{ number_format($item->bangun_rumah, 0, ".", ".")}}</td>
                                <td align="center">
                                    <form action="{{ route('admin.kelompok.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.kelompok.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/kelompok/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Kelompok
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Kelompok</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.kelompok.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Kelompok</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->kelompok}}" name="kelompok" class="form-control" placeholder="Kelompok / Tahap">
                                    <small class="text-danger">{{ $errors->first('kelompok') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jumlah Setoran</label>

                                <div class="col-sm-8">
                                    <input type="number" value="{{$data->jml_setoran}}" name="jml_setoran" class="form-control" placeholder="Jumlah Setoran">
                                    <small class="text-danger">{{ $errors->first('jml_setoran') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pembangunan Rumah</label>

                                <div class="col-sm-8">
                                    <input type="number" value="{{$data->bangun_rumah}}" name="bangun_rumah" class="form-control" placeholder="Pembangunan Rumah">
                                    <small class="text-danger">{{ $errors->first('bangun_rumah') }}</small>
                                </div>
                            </div>
                            <a href="{{url('admin/kelompok')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection