routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::get('home', 'HomeController@index');
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/tahun', 'Web\Admin\TahunController', ['as' => 'admin']);
Route::resource('admin/bulan', 'Web\Admin\BulanController', ['as' => 'admin']);
Route::resource('admin/kelompok', 'Web\Admin\KelompokController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::resource('admin/triwulan', 'Web\Admin\TriwulanController', ['as' => 'admin']);
Route::resource('admin/tahfidz', 'Web\Admin\TahfidzController', ['as' => 'admin']);
Route::resource('admin/rubah', 'Web\Admin\RubahController', ['as' => 'admin']);

Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');

Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/akadbarang', 'Web\Admin\AkadBarangController', ['as' => 'admin']);
Route::resource('admin/bangunrumah', 'Web\Admin\BangunRumahController', ['as' => 'admin']);
Route::get('admin/akadbarang/index/{id}', 'Web\Admin\AkadBarangController@index', ['as' => 'admin']);
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('admin/upload/regsim', 'Web\Admin\UploadController@regsim')->name('admin.upload.regsim');
Route::post('admin/import/regsim', 'Web\Admin\UploadController@import_regsim')->name('admin.import.regsim');

Route::get('admin/upload/regpem', 'Web\Admin\UploadController@regpem')->name('admin.upload.regpem');
Route::post('admin/import/regpem', 'Web\Admin\UploadController@import_regpem')->name('admin.import.regpem');

Route::get('admin/upload/bangunrumah', 'Web\Admin\UploadController@bangunrumah')->name('admin.upload.bangunrumah');
Route::post('admin/import/bangunrumah', 'Web\Admin\UploadController@import_bangunrumah')->name('admin.import.bangunrumah');

Route::get('admin/triwulan/show/{id}/{tw}', 'Web\Admin\TriwulanController@show_triwulan')->name('admin.triwulan.show.tw');
Route::get('admin/tahfidz/show/{id}/{tw}', 'Web\Admin\TahfidzController@show_tahfidz')->name('admin.tahfidz.show.tw');

resources/views/admin/bangun/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Bangun Rumah
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Bangun Rumah</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.bangunrumah.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Anggota</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="anggota_id">
                                        @foreach($kelompok as $kel)
                                        @foreach($kel->anggota->sortBy('nama') as $anggota)
                                        <option value="{{$anggota->id}}">{{$kel->kelompok}} | {{$anggota->nama}}</option>
                                        @endforeach
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('anggota_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Triwulan</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="tw">
                                        <option value="tw1">Triwulan 1</option>
                                        <option value="tw2">Triwulan 2</option>
                                        <option value="tw3">Triwulan 3</option>
                                        <option value="tw4">Triwulan 4</option>
                                    </select>
                                    <small class="text-danger">{{ $errors->first('tw') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kelompok</th>
                                <th>Triwulan</th>
                                <th>Nama</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->anggota->kelompok->kelompok }}</td>
                                <td>
                                    @if($item->tw==='tw1')
                                    Triwulan 1
                                    @elseif($item->tw==='tw2')
                                    Triwulan 2
                                    @elseif($item->tw==='tw3')
                                    Triwulan 3
                                    @elseif($item->tw==='tw4')
                                    Triwulan 4
                                    @else
                                    @endif
                                </td>
                                <td>{{ $item->anggota->nama }}</td>
                                <td align="center">
                                    <form action="{{ route('admin.bangunrumah.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.bangunrumah.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/bangun/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Bangun Rumah
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Bangun Rumah</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.bangunrumah.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Anggota</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="anggota_id">
                                        <option value="{{$data->anggota_id}}">{{$data->anggota->kelompok->kelompok}} | {{$data->anggota->nama}}</option>
                                        @foreach($kelompok as $kel)
                                        @foreach($kel->anggota->sortBy('nama') as $anggota)
                                        <option value="{{$anggota->id}}">{{$kel->kelompok}} | {{$anggota->nama}}</option>
                                        @endforeach
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('anggota_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Triwulan</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="tw">
                                        <option value="{{$data->tw}}">
                                            @if($data->tw==='tw1')
                                            Triwulan 1
                                            @elseif($data->tw==='tw2')
                                            Triwulan 2
                                            @elseif($data->tw==='tw3')
                                            Triwulan 3
                                            @elseif($data->tw==='tw4')
                                            Triwulan 4
                                            @else
                                            @endif
                                        </option>
                                        <option value="tw1">Triwulan 1</option>
                                        <option value="tw2">Triwulan 2</option>
                                        <option value="tw3">Triwulan 3</option>
                                        <option value="tw4">Triwulan 4</option>
                                    </select>
                                    <small class="text-danger">{{ $errors->first('tw') }}</small>
                                </div>
                            </div>

                            <a href="{{url('admin/bangunrumah')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection